### ISSUE TITLE
dirrections

### ISSUE THREAD

**Issue by Durman** [robert/wavefunction-collapse#6]
It looks like directions are taken in standard way. X is horizontal axis and Y is vertical.

https://github.com/robert/wavefunction-collapse/blob/093d218e79f01cbb7787b898b458cc5d174ad7cb/main.py#L5-L8

But as far as I know iteration over matrixes is happening first over Y axis and then over X.

https://github.com/robert/wavefunction-collapse/blob/093d218e79f01cbb7787b898b458cc5d174ad7cb/main.py#L317-L347

**Comment by robert** [comment]
Hi @Durman - thanks for the issue. I think I see what you mean. I'll try to find time to fix it, or I'd happily receive a PR!
